# Generated by Django 4.2.2 on 2023-06-26 13:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_vk_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='vk_user',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='vk_user',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона клиента'),
        ),
    ]
