# Generated by Django 4.2.2 on 2023-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_vk_user_email_vk_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vk_user',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя пользователя'),
        ),
    ]
