# Generated by Django 4.2.2 on 2023-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0005_alter_vk_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vk_user',
            name='cart',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Корзина для покупок'),
        ),
    ]
