# Generated by Django 4.2.2 on 2023-06-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_alter_vk_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vk_user',
            name='email',
        ),
    ]
