# Generated by Django 4.2.2 on 2023-06-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0007_remove_vk_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='datacenter.vk_user', verbose_name='Заказчик'),
        ),
    ]
