# Generated by Django 4.2.2 on 2023-06-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0011_alter_orderelements_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment', 'Проверка платежа'), ('first', 'Обработка'), ('second', 'Доставка'), ('third', 'Доставлен'), ('canceled', 'Отменён')], default='payment', max_length=100, verbose_name='Статус'),
        ),
    ]
